apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-flask-demo
  labels:
     name: kube-flask-demo
  #namespace: kube-system
spec:
  replicas: 3
  selector:
    name: rc-flask-demo
  template:
    metadata:
      labels:
          name: rc-flask-demo
    spec:
        volumes:
        - name: data
          emptyDir: {}
        containers:
        - image: registry.cn-hangzhou.aliyuncs.com/flask-demo/flask-demo:1.0
          name: flask-demo
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: data
            mountPath: /var/app
        - image: registry.cn-hangzhou.aliyuncs.com/flask-demo/flask-demo:git-update
          name: flask-demo-git-update
          volumeMounts:
          - name: data
            mountPath: /var/github
