apiVersion: v1
kind: Service
metadata:
  name: rc-flask-demo-service
  labels:
    name: rc-flask-demo-server
spec:
  selector:
    name: rc-flask-demo
  type: NodePort
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000
     nodePort: 30002