FROM ubuntu:16.04

WORKDIR /var
ARG http_proxy
ARG https_proxy

RUN echo '\
deb http://mirrors.aliyun.com/ubuntu/ xenial main restricted \
deb-src http://mirrors.aliyun.com/ubuntu/ xenial main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial multiverse\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates multiverse\
deb http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse #Added by software-properties\
deb http://archive.canonical.com/ubuntu xenial partner\
deb-src http://archive.canonical.com/ubuntu xenial partner\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security multiverse \'>/etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y git wget --fix-missing

ENV GIT_SSL_NO_VERIFY 1

ENV GIT_DISCOVERY_ACROSS_FILESYSTEM 1

RUN mkdir /var/github && chmod -R 0777 /var/github

VOLUME ["/var/github"]

ADD run.sh ./run.sh
RUN apt-get install -y wget iputils-ping

CMD chmod +x ./run.sh && ./run.sh

