FROM ubuntu:16.04

WORKDIR /var
#ARG http_proxy
#ARG https_proxy

RUN echo '\
deb http://mirrors.aliyun.com/ubuntu/ xenial main restricted \
deb-src http://mirrors.aliyun.com/ubuntu/ xenial main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial multiverse\
deb http://mirrors.aliyun.com/ubuntu/ xenial-updates multiverse\
deb http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse #Added by software-properties\
deb http://archive.canonical.com/ubuntu xenial partner\
deb-src http://archive.canonical.com/ubuntu xenial partner\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted\
deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted multiverse universe #Added by software-properties\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security universe\
deb http://mirrors.aliyun.com/ubuntu/ xenial-security multiverse \'>/etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y git --fix-missing

RUN git clone https://github.com/liao-bo/flask-demo.git

VOLUME ["/var/flask-demo"]

CMD while true; do sleep 30 && cd /var/flask-demo && git pull; done

